apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test"
  annotations:
    github.com/project-slug: undefined/undefined
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: "group:default/sx-cnp-oss"
